### ISSUE TITLE
Using the preamble from a different folder

### ISSUE THREAD

**Issue by racerand** [SSoelvsten/LaTeX-Preamble_and_Examples#1]
I ran into the issue of not being able to use the preamble directly when using it from a different folder. I have found a solution to this problem, by making making a new command: `\newcommand{\CommonPath}{yourPath}` in your new document where `yourPath` is the path to where the preamble is located. Then you just use `\input{\CommonPath/preamble_en.tex}` in the document and `\input{\CommonPath/preamble_base.tex}` in `preamble_en.tex`. I would think that this would be a nice inclusion, but it does make starting a new document a bit harder as `\CommonPath` would need to be defined each time.

**Comment by SSoelvsten** [comment]
Have you managed to do this with absolute or only with relative paths? I can't seem to link it directly to my local github version by using an absolute path.
Also, is the preamble in a subfolder or outside? I can't seem to use a relative path in _\input_ version to go "up" a directory
__________________

Having looked around for a little bit you would need the _import_ package to do absolute paths, and I got that to work quite quickly.

```tex
\documentclass[a4, danish]{article}
\usepackage{import}
\import{XXXX/GitHub/LaTeX_Preamble_and_Examples/preamble/}{preamble_en.tex}
```

The same package also supports relative paths with the _\subimport_ , which does allow going up in the directory tree.

```tex
\documentclass[a4, danish]{article}
\usepackage{import}
\subimport{../preamble/}{preamble_en.tex}
```
__________________

I'd think you would put the preamble_base.tex and preamble_en.tex in the same folder as the preamble_base.tex, so I don't think that would be necessary to include on that one, but definitely in the loading of the preamble.

Am I right in this assumption, or are there cases, in which that would change?

**Comment by racerand** [comment]
Exactly what I was thinking. was looking into import myself but could not get it to work correctly. Even looked through the documentation but probably just misunderstood how to use it. Great job.
